name: deploy cloudflare pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Zine
        uses: kristoff-it/setup-zine@v1
        with:
          version: v0.11.2

      - name: Build
        run: zine release

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public/ --project-name library99
          githubToken: ${{ secrets.GITHUB_TOKEN }}
